variable "aws_access_key" {}
variable "aws_secret_key" {}

variable "aws_region" {
  description = "AWS region to launch servers."
  default = "us-east-1"
}

variable "aws_az1" {
  description = "AWS availability zone 1"
  default = "us-east-1e"
}

variable "aws_az2" {
  description = "AWS availability zone 2"
  default = "us-east-1a"
variable "rails_secret_key_base" {
  description = "Secret key base for Rails. Generated by running \"rake secret\""
}

variable "rds_password" {}
